import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  Description,
  card,
  code,
  container,
  footer,
  grid,
  gridStyle,
  logo,
  main,
  title,
} from "../styles/pages/index.css";

type Post = {
  userId: number;
  id: number;
  title: string;
  body: string;
};

export async function getServerSideProps(_context: GetServerSidePropsContext) {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data: Post[] = await res.json();

  return {
    props: { data },
  };
}

type HomeProps = {
  data: Post[];
};

const Home: NextPage<HomeProps> = ({ data }) => {
  return (
    <div css={container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={main}>
        <h1 css={title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {/* <div>
          {data.map((post) => (
            <div key={post.id}>
              <h2>{post.title}</h2>
              <p>{post.body}</p>
            </div>
          ))}
        </div> */}

        <Description>
          Get started by editing <code css={code}>pages/index.tsx</code>
        </Description>

        <div css={[grid, gridStyle]}>
          <a href="https://nextjs.org/docs" css={card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" css={card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            css={card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            css={card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer css={footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span css={logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
